### ISSUE TITLE
rootfs file ownership is not preserved

### ISSUE THREAD

**Issue by evildeeds** [DanielMartensson/STM32-OS#1]
GIT only stores some basic permissions; GIT does not store file ownership (UID/GID) or SUID/GUID or any extended ACLs.

For example `su`, `sudo` neither have the suid bit set properly nor the correct owner UID (except the UID will be ok if you did git checkout as root... which you shouldn't) this prevents you from switching to `root` from `user` later.

Then there are some minor issues that the ext4 raw image is slightly  too small, that may however be related to my host system default block size.

Here is what works for me but I had fix permissions manually before building the image; the acl-file can be compressed if needed before adding it to the repository.

```bash
#!/bin/bash

# Remove old
rm rootfs.ext4

# Make file
dd if=/dev/zero of=rootfs.ext4 bs=1M count=3000

# Make filesystem
mkfs.ext4 rootfs.ext4

# Create folder
sudo mkdir /mnt/rootfs

# Mount
sudo mount -o loop rootfs.ext4 /mnt/rootfs

# Go inside
cd rootfs

# Fill except /proc
sudo cp -a bin home/ media/ opt/ root/ sbin usr/ boot/ etc/ lib mnt/ srv/ tmp/ var/ dev/ run/ sys/ /mnt/rootfs/

# Restore file ownership and permissions
sudo setfacl --restore=../rootfs.facl

# Umount
sudo umount /mnt/rootfs

# Get out
cd ..
```
Or as a Makefile; there are lots more to improve here, extracting the file list first and adding all files as a dependency for `rootfs.ext4` make rule.

```make
#!/bin/env make

.PHONY: all apply-acl create-acl
all: rootfs.ext4

rootfs.ext4: rootfs.facl
	sudo true
	dd if=/dev/zero of=$@ bs=1M count=3000
	mkfs.ext4 $@
	mkdir -p $@.mount
	sudo mount -o loop $@ $@.mount
	sudo cp -dR rootfs/* $@.mount/
	cat rootfs.facl | (cd $@.mount && sudo setfacl --restore=-)
	sudo umount $@.mount
	rm -d $@.mount

# recreate acl file as needed; this file should already be included in the repository
rootfs.facl:
	(cd rootfs && getfacl -PRn .) > $@

# force recreate acl file for checkin after locally editing file permissions
create-acl:
	$(MAKE) --always-make rootfs.facl

# apply acl after checkout and before locally editing file permissions
apply-acl: rootfs.facl
	cat rootfs.facl | (cd rootfs && sudo setfacl --restore=-)
```

**Comment by DanielMartensson** [comment]
Thank you! Can you do a PR? @evildeeds

**Comment by evildeeds** [comment]
Sure; just one thing, I'm not too keen on providing my rootfs acl-file, if you still have the original file permissions, since mine is quite the patch work and I'm sure I did not get all permissions correctly. Look at my suggested Makefile for instructions on how to create it.

**Comment by evildeeds** [comment]
Looks good; now then it seems that you had empty directories and device-files which you cannot add to git either - I'll open a new issue for that, this issue with file ownership and permissions is now solved
